title: "Cyber Jekyll"
description: "A personal website template built with Jekyll for GitHub Pages."
baseurl: "/Cyber-jekyll" # Base URL for the site
url: "https://lamin-sudo.github.io/Cyber-jekyll" # Replace with your GitHub Pages URL
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap # Added sitemap plugin for better SEO
markdown: kramdown
highlighter: rouge
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - README.md
  - _site # Exclude the generated site folder

